piraeusdatastore/piraeus

deploy.template/funcs.lib.yml, deploy/controller.yaml
Fixes the following error:
Error while dialing dial tcp: lookup piraeus-etcdpiraeus on 10.96.0.10:53: no such host
=> Remove trailing 'piraeus' from etcdendpoint

deploy.template/controller.yaml, deploy.template/csi.yaml, deploy.template/etcd.yaml, deploy.template/funcs.lib.yml, deploy.template/node.yaml, deploy/controller.yaml, deploy/csi.yaml, deploy/etcd.yaml, deploy/node.yaml
Due to https://github.com/kubernetes/kubernetes/issues/60596, we cannot
use 'priorityClass: system-node-critical' with Kubernetes versions prior
to 1.17.
=> Switch to using kube-system namespace

deploy.template/config.yml, deploy.template/funcs.lib.yml, deploy.template/node.yaml, deploy/node.yaml
Alternatively, we could just have one config option that disables the host mapping of linstor and lvm.
=> Make mapping of host LVM directories optional

README.md, demo/demo-pvc.yaml, demo/mysql/create-mysql.sh, deploy.template/10_etcd.yaml, deploy.template/20_controller.yaml, deploy.template/30_node.yaml, deploy.template/31_scaler.yaml, deploy.template/Makefile, deploy.template/config.yml, deploy.template/funcs.lib.yml, deploy/10_etcd.yaml, deploy/20_controller.yaml, deploy/30_node.yaml, deploy/31_scaler.yaml, deploy/all.cn.yaml, deploy/all.dce.yaml, deploy/all.yaml, dockerfiles/piraeus-init/Dockerfile, dockerfiles/piraeus-init/bin/cli.drbdadm.sh, dockerfiles/piraeus-init/bin/cli.linstor.sh, dockerfiles/piraeus-init/bin/init-node.sh, dockerfiles/piraeus-init/bin/init-scaler.sh, dockerfiles/piraeus-init/bin/run-scaler.sh
1. explicitly specify drbd image url
2. mapped etcd data dir to host
3. added drbdadm cli to host
4. fixed drbd v9.0.22 kmod compiling issue on Ubuntu 16
5. fixed a readme error about piraeus node label
=> Explicitly specify drbd-driver-loader image, and more

dockerfiles/piraeus-server/Dockerfile, dockerfiles/piraeus-server/Makefile
This entrypoint enables multiple replicas for LINSTOR controllers.
The basic principle is that only one controller is running at any
point in time. k8s leader election is used to coordinate which pod
gets to start the controller process.
If a controller dies or loses leader status another way, the process
is killed and another pod get to start the controller process.
Required for https://github.com/piraeusdatastore/piraeus-operator/issues/56
=> add k8s-await-election helper to piraeus server

.github/workflows/build-piraeus-server.yaml, dockerfiles/piraeus-server/Dockerfile, dockerfiles/piraeus-server/Makefile, dockerfiles/piraeus-server/VERSION.env
Add github workflow to push new piraeus-server images to:
* quay.io/piraeusdatastore
* docker.io/piraeusdatastore
To fix the version used, linstor components are now pinned to a specific
version. That version is also used as image tag.
=> automatic CI builds for piraeus-server images

.github/workflows/build-injector.yaml, .github/workflows/build-piraeus-client.yaml, .github/workflows/build-piraeus-server.yaml
Add a second registry target with separate login credentials for
* kernel injector images
* piraeus-client
* piraeus-server
=> Update github workflow to also push to docker hub

dockerfiles/piraeus-server/Dockerfile
In some Kubernetes contexts (OpenShift) we are not allowed to run as
root by default. This means that the controller may not have the required
permissions to create the log directoy.
This change manually creates the controller log directory and makes it
group-writable. Since we can ensure that the container user is a member of
this group (even as unprivileged SA in Openshift), this allows the controller
to write logs on all platforms.
Note that this is not an issue for satellites, as they always start as
privileged containers, i.e. they run as UID 0.
See https://github.com/piraeusdatastore/piraeus-operator/issues/123
=> piraeus-server: make controller log group-writable

dockerfiles/piraeus-server/Dockerfile, dockerfiles/piraeus-server/preferences
This switches from the self-patched lvm2 to the one from testing, which
contains the fix in question.
While at it, rm buster-backports and also take zfsutils-linux from
testing.
=> piraeus-server: lvm2 from bullseye

dockerfiles/piraeus-server/Makefile
This version of k8s-await-election can set the "nodeName" attribute
on created endpoint resources. This enables Kubernetes "hairpin mode",
which is required for a pod to access it's own service.
This allows "linstor ..." commands from the controller container to succeed.
Previously they would never receive a response from the controller.
=> piraeus-server: use k8s-await-election v0.2.3

dockerfiles/piraeus-server/Dockerfile
Enable logging to files for LINSTOR controller and satellite. The default
(only logging to stdout) meant that sos-reports would not contain any logs.
The default file backend that is configured but not enabled uses log rotation
(keep up to 10 log artifacts, each limited to 2MB), which should be a good
default for most environments.
See https://github.com/piraeusdatastore/piraeus-operator/issues/166
=> Ensure LINSTOR components log to files

dockerfiles/piraeus-server/Dockerfile
GOARCH!=$(dpkg --get-architecture) for at least ppc64le
see https://github.com/piraeusdatastore/piraeus/pull/85#discussion_r692145200
=> get GOARCH from docker, not from debian

.github/workflows/build-drbd-reactor.yaml, .github/workflows/build-injector.yaml, dockerfiles/drbd-driver-loader/Makefile
See #74
I changed the `Makefile`s to build for the local architecture on `make update` and build for all specified architectures on `make upload`.
=> enable multi-arch build for -reactor and -injector

dockerfiles/piraeus-server/Dockerfile
thin-send-recv and zstd are required for backup shipping, but weren't
installed. This commit adds them to the install list, and also adds
some documentation around which package is required for what.
Fixes https://github.com/piraeusdatastore/piraeus-operator/issues/250
=> docker: add dependencies for backup shipping

dockerfiles/piraeus-server/entry.sh
Automatically import PEM-certificates into Java keystore.
As part of https://github.com/piraeusdatastore/piraeus-operator/pull/262
=> Autoimport PEM certificates

dockerfiles/drbd-driver-loader/Dockerfile.almalinux8, dockerfiles/drbd-driver-loader/Dockerfile.centos7
AlmaLinux no longer includes insmod in the base image, but it is needed
for the drbd loader to work. So we have to make sure it is installed.
The dependency was also added to the centos7 image, for completeness.
=> ensure kmod tools are installed on centos/alma

dockerfiles/piraeus-server/entry.sh
It seems sometimes emptyDir can hold old keystore files, it's better to make sure that it does not contain anything before importing new certificates and keys.
fixes https://github.com/LINBIT/linstor-server/issues/279
=> Remove keystore before importing PEM certificates

dockerfiles/drbd-reactor/Dockerfile, dockerfiles/piraeus-client/Dockerfile, dockerfiles/piraeus-server/Dockerfile
The distro names used reflected a wrong naming on the LINBIT public repo
side of things. This got fixed, also fix them here.
While at it make it a bit more comfortable to switch distros by
introducing an ARG.
=> Dockerfiles: fix distro name

dockerfiles/drbd-reactor/Dockerfile, dockerfiles/piraeus-client/Dockerfile, dockerfiles/piraeus-server/Dockerfile
apt-key is deprecated and current stable is the last one supporting it.
Switch to /etc/apt/tusted.gpg.d/
Signed-off-by: Roland Kammerer <roland.kammerer@linbit.com>
=> Dockerfiles: stop using apt-key

dockerfiles/piraeus-server/Dockerfile
This is more robust than using sed at the cost of some readability in lvm.conf.
Since nobody should actually ever have to read or modify the lvm.conf in the
container any further, this was deemed a fine trade-off.
=> piraeus-server: use lvmconfig to change lvm.conf

dockerfiles/drbd-driver-loader/Dockerfile.focal
Ubuntu Focal uses the Jammy kernel for it's HWE kernel. To compile against the
newer kernel, you need elfutils installed.
Closes #118
=> drbd-loader: add elfutils to focal

dockerfiles/piraeus-server/Dockerfile
/var/lib/drbd/node_id is regenerated every time the container restarts, making the usage count not very useful.
Also includes a style fix in another commit
=> piraeus-server: disable usage count for DRBD utils

dockerfiles/piraeus-server/entry.sh
dmeventd will be started by lvm commands (i.e. lvcreate, lvremove, ..) if it does not already run. This is an issue if started in a context with a high soft file limit: dmeventd will try to close _all_ FDs after forking. The limit on Almalinux9 is higher than 1_000_000_000, which caused the initial command to wait for over 100 seconds, mostly leading to linstor commands timing out.
The workaround here is to start "dmeventd" before starting the satellite with a known reasonable file limit.
See also [0c6c6ec0d1d1d38320f66295d9f992ea8ee50815](https://github.com/LINBIT/linstor-server/commit/0c6c6ec0d1d1d38320f66295d9f992ea8ee50815) in the linstor-server project.
=> piraeus-server: start dmeventd on start-up

dockerfiles/piraeus-server/entry.sh
The file limit parsing introduced in 2b2ec174bcd contains bash-isms. In order to stay true to upstream, we simply change our current script to bash as well.
=> piraeus-server: fix prlimit parsing

dockerfiles/drbd-driver-loader/Dockerfile.bullseye, dockerfiles/drbd-driver-loader/Dockerfile.buster, dockerfiles/drbd-driver-loader/Makefile
This adds images for bullseye and buster. I haven't tested this on buster, but I had tested the bullseye image yesterday and it worked fine.
=> Debian drbd-driver-loader support

dockerfiles/piraeus-server/Dockerfile, dockerfiles/piraeus-server/entry.sh
We want to be able to run DB migrations for LINSTOR without having to start the full LINSTOR container. For this purpose, we add a new command to the entrypoint script, that:
* Checks the need for running migrations
* Creates a backup in the k8s API of the existing resources
* Runs the migrations
This command can be used as part of an init container in k8s.
=> docker,linstor: include migration script for k8s DB

dockerfiles/drbd-driver-loader/Dockerfile.bullseye, dockerfiles/drbd-driver-loader/Dockerfile.buster
Debian separates some build tools out of the normal source directory. Without these tools, we cannot build a kernel module. The current "fix" was to mount /usr/lib from the host, but that predictably breaks other distros, as we create a franken-container that way.
The better fix is to install the linux-kbuild-* tools directly in the container.
=> docker,drbd: include kbuild tools in debian

dockerfiles/piraeus-server/Dockerfile, dockerfiles/piraeus-server/entry.sh
When running in a container, we cannot assume to have access to dmeventd. Up to now, we manually started dmeventd to work around an issue when running the container on systemd with high rlimits. See 2b2ec174bcde for details.
However, there is no need to start dmeventd at all: it's primary use for automatic resizing VGs and LVs doesn't fit the use in containers anyways. So we can just disable "monitoring" of LVs, which in turn should prevent dmeventd from being started by some random lvcreate.
Also, use "exec" to start the linstor processes: that way they get to be PID 1 in the container and they receive any SIGINTs generated by the container runtime.
=> docker: remove dmeventd dependency from linstor

dockerfiles/ktls-utils/Dockerfile
If a normal C program is started as PID 1, it will not have the default SIGTERM handler installed: instead the signal will be ignored. This means that during container shutdown, the container will run until forceful shutdown via SIGKILL.
To work around this issue, we use "tini", a tiny init system for containers to act as PID 1 in the container. This way, tlshd is started as PID 2 and gets the normal SIGTERM handling, as tini will forward these signals.
This is only needed for ktls-utils:
* drbd-reactor has custom SIGTERM handling.
* LINSTOR inherits SIGTERM handling via the JVM.
=> docker: use "tini" when starting tlshd

dockerfiles/drbd-reactor/Dockerfile, dockerfiles/piraeus-client/Dockerfile, dockerfiles/piraeus-server/Dockerfile
Some tools that interact with the kernel are not happy when using old tools on a new kernel. For example, turns out that resize2fs (the ext* resize tool) refuses to resize a mounted FS on a new kernel because the FS there reports some features it does not know about.
To fix, we use the latest debian stable release as our base image. Tools there should be new enough for the future.
See https://github.com/piraeusdatastore/piraeus-operator/issues/628
=> docker: switch base to debian 12

dockerfiles/base.Dockerfile, dockerfiles/docker-bake.hcl, dockerfiles/drbd-reactor/Dockerfile, dockerfiles/ktls-utils/Dockerfile, dockerfiles/piraeus-server/Dockerfile
In order to configure the LINBIT repositories, we need to install the linbit-keyring package. This requires some set up as we need to fetch the package and then set up the repositories.
To make this nicer to work with, we use a single base docker image as the root of all builds.
While at it, also make use of proper tmpfs and cache mounts, so we do not add unnecessary files into the image layers.
=> docker: use common base image

dockerfiles/piraeus-server/entry.sh
There is a limit of around 1MB per resource in kubernetes. Big clusters might need to make DB backups that are larger than that. We improve our current solution in two ways:
* Provide a meaningful output should the run-migration not succeed. Instead of crashing by default, print what needs to be done to stderr and wait. Waiting can be skipped with an environment variable.
* Try to split the backup into smaller chunks, that can be reassembled on restore.
=> piraeus-server: deal with large backups

dockerfiles/docker-bake.hcl
* LINSTOR 1.29.2
* DRBD Reactor 1.5.0
=> docker: LINSTOR and DRBD Reactor releases

dockerfiles/docker-bake.hcl, dockerfiles/drbd-driver-loader/Dockerfile.trixie
I tested it by building it manually on debian 13, and it works well.
This is just a copy of the bullseye dockerfile with the codename changed.
Thank you for your work.
=> docker: debian 13 drbd-loader

dockerfiles/drbd-driver-loader/Dockerfile.almalinux8, dockerfiles/drbd-driver-loader/Dockerfile.bookworm, dockerfiles/drbd-driver-loader/Dockerfile.bullseye, dockerfiles/drbd-driver-loader/Dockerfile.jammy, dockerfiles/drbd-driver-loader/Dockerfile.noble, dockerfiles/drbd-driver-loader/Dockerfile.trixie
Private clouds often lack direct Internet access. If the `spatch` binary is missing and Spatch-as-a-Service is unavailable, `drbd-module-loader` cannot patch the DRBD sources and build `drbd.ko`.
This pull request adds a step to the Dockerfiles to install `spatch` (provided by the `coccinelle` package). The `coccinelle` package is available on Debian-based distributions and on AlmaLinux 8 via EPEL 8.
=> Bundle `spatch` in container to apply patches locally
